name: publish to github pages

on:
  push:
    branches: [ main ]

# Cancel already running jobs
concurrency:
  group: publish_to_pages_${{ github.head_ref }}
  cancel-in-progress: true

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    environment:
      name: github-pages
      #url: ${{ steps.deployment.outputs.page_url }}
      url: ${{ steps.setup_pages.outputs.base_url }}
    name: "publish webpage"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Pages
      uses: actions/configure-pages@v4
      id: setup_pages
    - name: Upload pages
      uses: actions/upload-pages-artifact@v3
      with:
        path: 'web'
    - name: Deploy pages
      uses: actions/deploy-pages@v4
